import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { actualizarEstadoMaquinaria, crearGasto, crearMantenimiento, eliminarGasto, eliminarMantenimiento, eliminarMaquinaria, getMaquinaria } from '@/api/maquinarias.api';
import { getApiErrorMessage } from '@/api/errors';
import { useAuthStore } from '@/store/auth.store';
import { ESTADO_MAQUINARIA_LABEL, ESTADOS_MAQUINARIA, TIPO_GASTO_LABEL, TIPO_MANTENIMIENTO_LABEL, TIPOS_GASTO, TIPOS_MANTENIMIENTO, type EstadoMaquinaria, type TipoGastoMaquinaria, type TipoMantenimiento } from '@/types/maquinarias';

const today = () => new Date().toISOString().slice(0, 10);

export default function MaquinariaDetalleScreen() {
  const { maquinariaId } = useLocalSearchParams<{ maquinariaId: string }>();
  const maquinariaIdNumber = Number(maquinariaId);
  const organizacionActivaId = useAuthStore((state) => state.organizacionActivaId);
  const queryClient = useQueryClient();
  const [maintenanceType, setMaintenanceType] = useState<TipoMantenimiento>('CAMBIO_ACEITE'); const [maintenanceDate, setMaintenanceDate] = useState(today()); const [maintenanceCost, setMaintenanceCost] = useState(''); const [maintenanceHours, setMaintenanceHours] = useState(''); const [maintenanceDescription, setMaintenanceDescription] = useState(''); const [expenseType, setExpenseType] = useState<TipoGastoMaquinaria>('COMBUSTIBLE'); const [expenseDate, setExpenseDate] = useState(today()); const [expenseAmount, setExpenseAmount] = useState(''); const [expenseDescription, setExpenseDescription] = useState('');
  const machineQuery = useQuery({ queryKey: ['maquinaria', maquinariaIdNumber], queryFn: () => getMaquinaria(maquinariaIdNumber), enabled: Boolean(maquinariaIdNumber) });
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['maquinarias', organizacionActivaId] }), queryClient.invalidateQueries({ queryKey: ['maquinaria', maquinariaIdNumber] })]); };
  const statusMutation = useMutation({ mutationFn: (estado: EstadoMaquinaria) => actualizarEstadoMaquinaria(maquinariaIdNumber, estado), onSuccess: refresh, onError: (error: unknown) => Alert.alert('No pudimos actualizar el estado', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const deleteMachineMutation = useMutation({ mutationFn: () => eliminarMaquinaria(maquinariaIdNumber), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['maquinarias', organizacionActivaId] }); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos eliminar la maquinaria', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const maintenanceMutation = useMutation({ mutationFn: () => crearMantenimiento(maquinariaIdNumber, { tipo: maintenanceType, fecha: maintenanceDate, costo: maintenanceCost ? Number(maintenanceCost) : undefined, horasUso: maintenanceHours ? Number(maintenanceHours) : undefined, descripcion: maintenanceDescription.trim() || undefined }), onSuccess: async () => { setMaintenanceCost(''); setMaintenanceHours(''); setMaintenanceDescription(''); await refresh(); }, onError: (error: unknown) => Alert.alert('No pudimos registrar el mantenimiento', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) });
  const expenseMutation = useMutation({ mutationFn: () => crearGasto(maquinariaIdNumber, { tipo: expenseType, fecha: expenseDate, monto: Number(expenseAmount), descripcion: expenseDescription.trim() }), onSuccess: async () => { setExpenseAmount(''); setExpenseDescription(''); await refresh(); }, onError: (error: unknown) => Alert.alert('No pudimos registrar el gasto', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) });
  const removeMaintenanceMutation = useMutation({ mutationFn: (id: number) => eliminarMantenimiento(maquinariaIdNumber, id), onSuccess: refresh, onError: (error: unknown) => Alert.alert('No pudimos eliminar el mantenimiento', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const removeExpenseMutation = useMutation({ mutationFn: (id: number) => eliminarGasto(maquinariaIdNumber, id), onSuccess: refresh, onError: (error: unknown) => Alert.alert('No pudimos eliminar el gasto', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const machine = machineQuery.data;
  const totalExpenses = useMemo(() => machine?.gastos.reduce((sum, expense) => sum + expense.monto, 0) ?? 0, [machine]);

  if (machineQuery.isLoading) return <Loading />;
  if (machineQuery.isError || !machine) return <LoadError error={machineQuery.error} onRetry={() => void machineQuery.refetch()} />;

  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Maquinarias</Text></Pressable><View className="mt-5 rounded-2xl bg-emerald-800 p-5"><Text className="text-3xl font-bold text-white">{machine.nombre}</Text><Text className="mt-2 text-sm text-emerald-100">{machine.tipo.replaceAll('_', ' ')}{machine.marca ? ` · ${machine.marca}` : ''}{machine.modelo ? ` ${machine.modelo}` : ''}</Text><View className="mt-5 flex-row gap-3"><Metric label="Horas" value={machine.horasUso !== null && machine.horasUso !== undefined ? `${machine.horasUso} hs` : '—'} /><Metric label="Gastos" value={money(totalExpenses)} /></View></View>
    <Section title="Estado operativo" description="Actualizá la disponibilidad real del equipo."><View className="flex-row flex-wrap gap-2">{ESTADOS_MAQUINARIA.map((item) => <Choice key={item} label={ESTADO_MAQUINARIA_LABEL[item]} active={machine.estado === item} onPress={() => statusMutation.mutate(item)} />)}</View>{machine.patente && <Text className="mt-4 text-sm text-slate-500">Patente / serie: {machine.patente}</Text>}{machine.observaciones && <Text className="mt-2 text-sm text-slate-500">{machine.observaciones}</Text>}</Section>
    <Section title="Mantenimientos" description="Registrá revisiones, reparaciones y horas de uso."><Text className="text-sm font-semibold text-slate-800">Nuevo mantenimiento</Text><ChoiceRow values={TIPOS_MANTENIMIENTO} selected={maintenanceType} label={(value) => TIPO_MANTENIMIENTO_LABEL[value]} onSelect={setMaintenanceType} /><Input value={maintenanceDate} onChangeText={setMaintenanceDate} placeholder="AAAA-MM-DD" /><View className="mt-3 flex-row gap-3"><View className="flex-1"><Input value={maintenanceCost} onChangeText={setMaintenanceCost} keyboardType="decimal-pad" placeholder="Costo opcional" /></View><View className="flex-1"><Input value={maintenanceHours} onChangeText={setMaintenanceHours} keyboardType="decimal-pad" placeholder="Horas opcionales" /></View></View><Input value={maintenanceDescription} onChangeText={setMaintenanceDescription} placeholder="Descripción opcional" /><Action label={maintenanceMutation.isPending ? 'Guardando…' : 'Registrar mantenimiento'} disabled={!/^\d{4}-\d{2}-\d{2}$/.test(maintenanceDate) || maintenanceMutation.isPending} onPress={() => maintenanceMutation.mutate()} />
      <List title="Historial" empty="Sin mantenimientos registrados.">{machine.mantenimientos.map((item) => <Record key={item.id} title={TIPO_MANTENIMIENTO_LABEL[item.tipo]} subtitle={`${date(item.fecha)}${item.costo !== null && item.costo !== undefined ? ` · ${money(item.costo)}` : ''}`} description={item.descripcion} onDelete={() => removeMaintenanceMutation.mutate(item.id)} />)}</List></Section>
    <Section title="Gastos" description="Registrá combustible, repuestos y servicios."><Text className="text-sm font-semibold text-slate-800">Nuevo gasto</Text><ChoiceRow values={TIPOS_GASTO} selected={expenseType} label={(value) => TIPO_GASTO_LABEL[value]} onSelect={setExpenseType} /><Input value={expenseDescription} onChangeText={setExpenseDescription} placeholder="Descripción del gasto" /><View className="mt-3 flex-row gap-3"><View className="flex-1"><Input value={expenseAmount} onChangeText={setExpenseAmount} keyboardType="decimal-pad" placeholder="Monto" /></View><View className="flex-1"><Input value={expenseDate} onChangeText={setExpenseDate} placeholder="AAAA-MM-DD" /></View></View><Action label={expenseMutation.isPending ? 'Guardando…' : 'Registrar gasto'} disabled={!expenseDescription.trim() || Number(expenseAmount) < 0 || !expenseAmount || !/^\d{4}-\d{2}-\d{2}$/.test(expenseDate) || expenseMutation.isPending} onPress={() => expenseMutation.mutate()} />
      <List title="Historial" empty="Sin gastos registrados.">{machine.gastos.map((item) => <Record key={item.id} title={`${TIPO_GASTO_LABEL[item.tipo]} · ${money(item.monto)}`} subtitle={date(item.fecha)} description={item.descripcion} onDelete={() => removeExpenseMutation.mutate(item.id)} />)}</List></Section>
    <Pressable className="mt-5 items-center rounded-xl bg-red-50 px-4 py-3" disabled={deleteMachineMutation.isPending} onPress={() => Alert.alert('Eliminar maquinaria', `¿Eliminar ${machine.nombre}? Esta acción no se puede deshacer.`, [{ text: 'Volver', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: () => deleteMachineMutation.mutate() }])}><Text className="font-semibold text-red-700">Eliminar maquinaria</Text></Pressable>
  </ScrollView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View className="flex-1 rounded-xl bg-emerald-700 p-3"><Text className="text-xs text-emerald-100">{label}</Text><Text className="mt-1 font-bold text-white">{value}</Text></View>; }
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <View className="mt-5 rounded-2xl bg-white p-5"><Text className="text-lg font-bold text-slate-900">{title}</Text><Text className="mt-1 text-sm text-slate-500">{description}</Text><View className="mt-4">{children}</View></View>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`rounded-full border px-3 py-2 ${active ? 'border-emerald-700 bg-emerald-700' : 'border-slate-200 bg-white'}`} onPress={onPress}><Text className={`text-sm font-semibold ${active ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>; }
function ChoiceRow<T extends string>({ values, selected, label, onSelect }: { values: T[]; selected: T; label: (value: T) => string; onSelect: (value: T) => void }) { return <View className="mt-2 flex-row flex-wrap gap-2">{values.map((value) => <Choice key={value} label={label(value)} active={selected === value} onPress={() => onSelect(value)} />)}</View>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; }
function Action({ label, disabled, onPress }: { label: string; disabled: boolean; onPress: () => void }) { return <Pressable className="mt-3 items-center rounded-xl bg-emerald-700 px-4 py-3 disabled:opacity-50" disabled={disabled} onPress={onPress}><Text className="font-semibold text-white">{label}</Text></Pressable>; }
function List({ title, empty, children }: { title: string; empty: string; children: React.ReactNode[] }) { return <View className="mt-6 border-t border-slate-100 pt-4"><Text className="text-sm font-semibold text-slate-800">{title}</Text>{children.length === 0 ? <Text className="mt-2 text-sm text-slate-500">{empty}</Text> : <View className="mt-3 gap-2">{children}</View>}</View>; }
function Record({ title, subtitle, description, onDelete }: { title: string; subtitle: string; description?: string | null; onDelete: () => void }) { return <View className="rounded-xl border border-slate-100 p-3"><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="font-semibold text-slate-800">{title}</Text><Text className="mt-1 text-sm text-slate-500">{subtitle}</Text>{description && <Text className="mt-1 text-sm text-slate-500">{description}</Text>}</View><Pressable onPress={() => Alert.alert('Eliminar registro', '¿Querés eliminar este registro?', [{ text: 'Volver', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: onDelete }])}><Text className="text-xs font-semibold text-red-600">Eliminar</Text></Pressable></View></View>; }
function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando maquinaria…</Text></View>; }
function LoadError({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar la maquinaria</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={onRetry}><Text className="font-semibold text-white">Reintentar</Text></Pressable></View>; }
function money(value: number) { return new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }
