import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { crearMaquinaria } from '@/api/maquinarias.api';
import { getApiErrorMessage } from '@/api/errors';
import { useAuthStore } from '@/store/auth.store';
import { ESTADO_MAQUINARIA_LABEL, ESTADOS_MAQUINARIA, TIPO_MAQUINARIA_LABEL, TIPOS_MAQUINARIA, type EstadoMaquinaria, type TipoMaquinaria } from '@/types/maquinarias';

export default function NuevaMaquinariaScreen() {
  const organizacionActivaId = useAuthStore((state) => state.organizacionActivaId);
  const queryClient = useQueryClient();
  const [nombre, setNombre] = useState(''); const [tipo, setTipo] = useState<TipoMaquinaria>('TRACTOR'); const [estado, setEstado] = useState<EstadoMaquinaria>('OPERATIVA'); const [marca, setMarca] = useState(''); const [modelo, setModelo] = useState(''); const [anio, setAnio] = useState(''); const [patente, setPatente] = useState(''); const [horasUso, setHorasUso] = useState(''); const [observaciones, setObservaciones] = useState('');
  const createMutation = useMutation({ mutationFn: () => crearMaquinaria({ nombre: nombre.trim(), tipo, estado, marca: marca.trim() || undefined, modelo: modelo.trim() || undefined, anio: anio ? Number(anio) : undefined, patente: patente.trim() || undefined, horasUso: horasUso ? Number(horasUso) : undefined, observaciones: observaciones.trim() || undefined }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['maquinarias', organizacionActivaId] }); Alert.alert('Equipo registrado', 'La maquinaria ya está disponible en la organización.'); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos registrar el equipo', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) });
  const valid = nombre.trim().length >= 2 && (!anio || Number.isInteger(Number(anio))) && (!horasUso || Number(horasUso) >= 0);
  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Maquinarias</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">Nueva maquinaria</Text><View className="mt-7 rounded-2xl bg-white p-5"><Label text="Nombre"><Input value={nombre} onChangeText={setNombre} placeholder="Ej: Tractor John Deere" /></Label><Text className="mt-6 text-sm font-semibold text-slate-800">Tipo</Text><View className="mt-2 flex-row flex-wrap gap-2">{TIPOS_MAQUINARIA.map((item) => <Choice key={item} label={TIPO_MAQUINARIA_LABEL[item]} active={tipo === item} onPress={() => setTipo(item)} />)}</View><Text className="mt-6 text-sm font-semibold text-slate-800">Estado</Text><View className="mt-2 flex-row flex-wrap gap-2">{ESTADOS_MAQUINARIA.map((item) => <Choice key={item} label={ESTADO_MAQUINARIA_LABEL[item]} active={estado === item} onPress={() => setEstado(item)} />)}</View><View className="mt-6 flex-row gap-3"><View className="flex-1"><Label text="Marca"><Input value={marca} onChangeText={setMarca} placeholder="Opcional" /></Label></View><View className="flex-1"><Label text="Modelo"><Input value={modelo} onChangeText={setModelo} placeholder="Opcional" /></Label></View></View><View className="mt-4 flex-row gap-3"><View className="flex-1"><Label text="Año"><Input value={anio} onChangeText={setAnio} keyboardType="number-pad" placeholder="Opcional" /></Label></View><View className="flex-1"><Label text="Patente / serie"><Input value={patente} onChangeText={setPatente} placeholder="Opcional" /></Label></View></View><Label text="Horas de uso" extra><Input value={horasUso} onChangeText={setHorasUso} keyboardType="decimal-pad" placeholder="Opcional" /></Label><Label text="Observaciones" extra><TextInput value={observaciones} onChangeText={setObservaciones} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Pressable className="mt-7 items-center rounded-xl bg-emerald-700 px-5 py-4 disabled:opacity-50" disabled={!valid || createMutation.isPending} onPress={() => createMutation.mutate()}><Text className="font-semibold text-white">{createMutation.isPending ? 'Registrando…' : 'Registrar maquinaria'}</Text></Pressable></View></ScrollView>;
}
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; }
function Label({ text, extra, children }: { text: string; extra?: boolean; children: React.ReactNode }) { return <View className={extra ? 'mt-4' : ''}><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`rounded-full border px-3 py-2 ${active ? 'border-emerald-700 bg-emerald-700' : 'border-slate-200 bg-white'}`} onPress={onPress}><Text className={`text-sm font-semibold ${active ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>; }
