import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { actualizarMovimiento, eliminarMovimiento, getMovimiento } from '@/api/finanzas.api';
import { getApiErrorMessage } from '@/api/errors';
import { useAuthStore } from '@/store/auth.store';
import { CATEGORIA_LABEL, EGRESO_CATEGORIAS, INGRESO_CATEGORIAS, type CategoriaMovimiento, type TipoMovimiento } from '@/types/finanzas';

export default function MovimientoDetalleScreen() {
  const { movimientoId } = useLocalSearchParams<{ movimientoId: string }>(); const id = Number(movimientoId); const orgId = useAuthStore((state) => state.organizacionActivaId); const qc = useQueryClient(); const query = useQuery({ queryKey: ['finanza', id], queryFn: () => getMovimiento(id), enabled: Boolean(id) }); const [tipo, setTipo] = useState<TipoMovimiento>('INGRESO'); const [concepto, setConcepto] = useState(''); const [monto, setMonto] = useState(''); const [fecha, setFecha] = useState(''); const [categoria, setCategoria] = useState<CategoriaMovimiento>('COSECHA'); const [observaciones, setObservaciones] = useState('');
  useEffect(() => { if (!query.data) return; setTipo(query.data.tipo); setConcepto(query.data.concepto); setMonto(String(query.data.monto)); setFecha(query.data.fecha.slice(0, 10)); setCategoria(query.data.categoria); setObservaciones(query.data.observaciones ?? ''); }, [query.data]);
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['finanzas', orgId] }), qc.invalidateQueries({ queryKey: ['finanzas-resumen', orgId] }), qc.invalidateQueries({ queryKey: ['finanza', id] })]); };
  const updateMutation = useMutation({ mutationFn: () => actualizarMovimiento(id, { tipo, concepto: concepto.trim(), monto: Number(monto), fecha, categoria, observaciones: observaciones.trim() || undefined }), onSuccess: async () => { await refresh(); Alert.alert('Movimiento actualizado', 'Los cambios se guardaron correctamente.'); }, onError: (error: unknown) => Alert.alert('No pudimos actualizar el movimiento', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) });
  const deleteMutation = useMutation({ mutationFn: () => eliminarMovimiento(id), onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['finanzas', orgId] }), qc.invalidateQueries({ queryKey: ['finanzas-resumen', orgId] })]); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos eliminar el movimiento', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const categories = tipo === 'INGRESO' ? INGRESO_CATEGORIAS : EGRESO_CATEGORIAS; const changeType = (next: TipoMovimiento) => { setTipo(next); setCategoria((next === 'INGRESO' ? INGRESO_CATEGORIAS : EGRESO_CATEGORIAS)[0]); }; const valid = concepto.trim().length >= 2 && Number(monto) > 0 && /^\d{4}-\d{2}-\d{2}$/.test(fecha);
  if (query.isLoading) return <Loading />; if (query.isError || !query.data) return <ErrorView error={query.error} onRetry={() => void query.refetch()} />;
  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Finanzas</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">Editar movimiento</Text><View className="mt-7 rounded-2xl bg-white p-5"><View className="flex-row gap-2"><Choice label="+ Ingreso" active={tipo === 'INGRESO'} onPress={() => changeType('INGRESO')} /><Choice label="- Egreso" active={tipo === 'EGRESO'} onPress={() => changeType('EGRESO')} /></View><Label text="Concepto"><Input value={concepto} onChangeText={setConcepto} /></Label><View className="mt-4 flex-row gap-3"><View className="flex-1"><Label text="Monto"><Input value={monto} onChangeText={setMonto} keyboardType="decimal-pad" /></Label></View><View className="flex-1"><Label text="Fecha"><Input value={fecha} onChangeText={setFecha} /></Label></View></View><Text className="mt-5 text-sm font-semibold text-slate-800">Categoría</Text><View className="mt-2 flex-row flex-wrap gap-2">{categories.map((item) => <Choice key={item} label={CATEGORIA_LABEL[item]} active={categoria === item} onPress={() => setCategoria(item)} />)}</View><Label text="Observaciones"><TextInput value={observaciones} onChangeText={setObservaciones} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Pressable className="mt-7 items-center rounded-xl bg-emerald-700 px-5 py-4 disabled:opacity-50" disabled={!valid || updateMutation.isPending} onPress={() => updateMutation.mutate()}><Text className="font-semibold text-white">{updateMutation.isPending ? 'Guardando…' : 'Guardar cambios'}</Text></Pressable><Pressable className="mt-4 items-center rounded-xl bg-red-50 px-5 py-4 disabled:opacity-50" disabled={deleteMutation.isPending} onPress={() => Alert.alert('Eliminar movimiento', '¿Querés eliminar este movimiento?', [{ text: 'Volver', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: () => deleteMutation.mutate() }])}><Text className="font-semibold text-red-700">Eliminar movimiento</Text></Pressable></View></ScrollView>;
}
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; } function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View className="mt-5"><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; } function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`rounded-full border px-3 py-2 ${active ? 'border-emerald-700 bg-emerald-700' : 'border-slate-200 bg-white'}`} onPress={onPress}><Text className={`text-sm font-semibold ${active ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>; }
function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando movimiento…</Text></View>; } function ErrorView({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar el movimiento</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={onRetry}><Text className="font-semibold text-white">Reintentar</Text></Pressable></View>; }
