import { ActivityIndicator, Pressable, RefreshControl, ScrollView, Text, View } from 'react-native';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Href, router } from 'expo-router';
import { getMovimientos, getResumenFinanzas } from '@/api/finanzas.api';
import { getApiErrorMessage } from '@/api/errors';
import { AccessRestricted } from '@/components/AccessRestricted';
import { useAuthStore } from '@/store/auth.store';
import { CATEGORIA_LABEL, type TipoMovimiento } from '@/types/finanzas';

export default function FinanzasScreen() {
  const organizacionActivaId = useAuthStore((state) => state.organizacionActivaId); const isOwner = useAuthStore((state) => state.isOwner()); const membresia = useAuthStore((state) => state.membresia); const membresiaOrganizacionId = useAuthStore((state) => state.membresiaOrganizacionId); const [type, setType] = useState<TipoMovimiento | null>(null);
  const ready = isOwner || membresiaOrganizacionId === organizacionActivaId; const canView = isOwner || membresia?.modulos.some((modulo) => modulo.moduloNombre === 'Finanzas' && modulo.activo) === true;
  const movementsQuery = useQuery({ queryKey: ['finanzas', organizacionActivaId], queryFn: getMovimientos, enabled: Boolean(organizacionActivaId && ready && canView) }); const summaryQuery = useQuery({ queryKey: ['finanzas-resumen', organizacionActivaId], queryFn: getResumenFinanzas, enabled: Boolean(organizacionActivaId && ready && canView) });
  const movements = useMemo(() => (movementsQuery.data ?? []).filter((movement) => !type || movement.tipo === type), [movementsQuery.data, type]); const refresh = async () => { await Promise.all([movementsQuery.refetch(), summaryQuery.refetch()]); };
  if (!ready || movementsQuery.isLoading || summaryQuery.isLoading) return <Loading />; if (!canView) return <AccessRestricted title="Finanzas" />; if (movementsQuery.isError || summaryQuery.isError) return <LoadError error={movementsQuery.error || summaryQuery.error} onRetry={() => void refresh()} />;
  const summary = summaryQuery.data!;
  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ paddingBottom: 32 }} refreshControl={<RefreshControl refreshing={movementsQuery.isRefetching || summaryQuery.isRefetching} onRefresh={() => void refresh()} />}><View className="bg-emerald-800 px-6 pb-7 pt-16"><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="text-3xl font-bold text-white">Finanzas</Text><Text className="mt-2 text-sm text-emerald-100">Ingresos, egresos y saldo del establecimiento.</Text></View><Pressable className="rounded-xl bg-white px-3 py-3" onPress={() => router.push('/(app)/finanzas/nuevo' as Href)}><Text className="font-semibold text-emerald-800">+ Movimiento</Text></Pressable></View></View><View className="px-5 pt-5"><View className="flex-row gap-3"><Metric label="Ingresos" value={money(summary.ingresos)} tone="positive" /><Metric label="Egresos" value={money(summary.egresos)} tone="negative" /></View><View className={`mt-3 rounded-2xl p-4 ${summary.saldo >= 0 ? 'bg-emerald-700' : 'bg-red-600'}`}><Text className="text-sm text-white/80">Saldo neto</Text><Text className="mt-1 text-2xl font-bold text-white">{money(summary.saldo)}</Text></View><View className="mt-6 flex-row gap-2"><Chip label="Todos" active={!type} onPress={() => setType(null)} /><Chip label="Ingresos" active={type === 'INGRESO'} onPress={() => setType(type === 'INGRESO' ? null : 'INGRESO')} /><Chip label="Egresos" active={type === 'EGRESO'} onPress={() => setType(type === 'EGRESO' ? null : 'EGRESO')} /></View><Text className="mt-7 text-sm font-bold uppercase tracking-widest text-slate-500">Movimientos ({movements.length})</Text><View className="mt-3 gap-3">{movements.length === 0 ? <Empty onAdd={() => router.push('/(app)/finanzas/nuevo' as Href)} /> : movements.map((movement) => <Pressable key={movement.id} className="rounded-2xl bg-white p-4" onPress={() => router.push({ pathname: '/(app)/finanzas/[movimientoId]', params: { movimientoId: String(movement.id) } } as unknown as Href)}><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="font-bold text-slate-900">{movement.concepto}</Text><Text className="mt-1 text-sm text-slate-500">{CATEGORIA_LABEL[movement.categoria]} · {date(movement.fecha)}</Text></View><Text className={`text-base font-bold ${movement.tipo === 'INGRESO' ? 'text-emerald-700' : 'text-red-600'}`}>{movement.tipo === 'INGRESO' ? '+' : '-'}{money(movement.monto)}</Text></View></Pressable>)}</View></View></ScrollView>;
}
function Metric({ label, value, tone }: { label: string; value: string; tone: 'positive' | 'negative' }) { return <View className="flex-1 rounded-2xl bg-white p-4"><Text className="text-sm text-slate-500">{label}</Text><Text className={`mt-1 text-lg font-bold ${tone === 'positive' ? 'text-emerald-700' : 'text-red-600'}`}>{value}</Text></View>; }
function Chip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable className={`rounded-full border px-3 py-2 ${active ? 'border-emerald-700 bg-emerald-700' : 'border-slate-200 bg-white'}`} onPress={onPress}><Text className={`text-sm font-semibold ${active ? 'text-white' : 'text-slate-700'}`}>{label}</Text></Pressable>; }
function Empty({ onAdd }: { onAdd: () => void }) { return <View className="items-center rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12"><Text className="text-4xl">$</Text><Text className="mt-4 text-lg font-bold text-slate-900">No hay movimientos registrados</Text><Pressable className="mt-5 rounded-xl bg-emerald-700 px-4 py-3" onPress={onAdd}><Text className="font-semibold text-white">Registrar movimiento</Text></Pressable></View>; }
function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando finanzas…</Text></View>; }
function LoadError({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar las finanzas</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={onRetry}><Text className="font-semibold text-white">Reintentar</Text></Pressable></View>; }
function money(value: number) { return new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value); } function date(value: string) { return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short' }).format(new Date(value)); }
