import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { actualizarCampania, asignarSiembrasCampania, eliminarCampania, getCampania } from '@/api/campanias.api';
import { getApiErrorMessage } from '@/api/errors';
import { getRecursosPorTipo } from '@/api/recursos.api';
import { useAuthStore } from '@/store/auth.store';

export default function CampaniaDetalleScreen() {
  const { campaniaId } = useLocalSearchParams<{ campaniaId: string }>(); const id = Number(campaniaId); const orgId = useAuthStore((state) => state.organizacionActivaId); const qc = useQueryClient(); const campaignQuery = useQuery({ queryKey: ['campania', id], queryFn: () => getCampania(id), enabled: Boolean(id) }); const seedsQuery = useQuery({ queryKey: ['recursos-campania-siembras', orgId], queryFn: () => getRecursosPorTipo('SIEMBRA'), enabled: Boolean(orgId) }); const [nombre, setNombre] = useState(''); const [inicio, setInicio] = useState(''); const [fin, setFin] = useState(''); const [descripcion, setDescripcion] = useState(''); const [selectedSeeds, setSelectedSeeds] = useState<number[]>([]);
  useEffect(() => { const campaign = campaignQuery.data; if (!campaign) return; setNombre(campaign.nombre); setInicio(campaign.fechaInicio.slice(0, 10)); setFin(campaign.fechaFin?.slice(0, 10) ?? ''); setDescripcion(campaign.descripcion ?? ''); setSelectedSeeds(campaign.siembras.map((seed) => seed.id)); }, [campaignQuery.data]);
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['campanias', orgId] }), qc.invalidateQueries({ queryKey: ['campania', id] })]); };
  const updateMutation = useMutation({ mutationFn: () => actualizarCampania(id, { nombre: nombre.trim(), fechaInicio: inicio, fechaFin: fin || undefined, descripcion: descripcion.trim() || undefined }), onSuccess: async () => { await refresh(); Alert.alert('Campaña actualizada', 'Los cambios se guardaron correctamente.'); }, onError: (error: unknown) => Alert.alert('No pudimos actualizar la campaña', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) });
  const assignMutation = useMutation({ mutationFn: () => asignarSiembrasCampania(id, selectedSeeds), onSuccess: async () => { await refresh(); Alert.alert('Siembras vinculadas', 'Las siembras seleccionadas fueron asignadas a esta campaña.'); }, onError: (error: unknown) => Alert.alert('No pudimos vincular las siembras', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const deleteMutation = useMutation({ mutationFn: () => eliminarCampania(id), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['campanias', orgId] }); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos eliminar la campaña', getApiErrorMessage(error, 'Intentá nuevamente.')) });
  const campaign = campaignQuery.data; const valid = nombre.trim().length >= 3 && /^\d{4}-\d{2}-\d{2}$/.test(inicio) && (!fin || /^\d{4}-\d{2}-\d{2}$/.test(fin));
  if (campaignQuery.isLoading) return <Loading />; if (campaignQuery.isError || !campaign) return <ErrorView error={campaignQuery.error} onRetry={() => void campaignQuery.refetch()} />;
  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Campañas</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">{campaign.nombre}</Text><Section title="Datos de la campaña"><Label text="Nombre"><Input value={nombre} onChangeText={setNombre} /></Label><View className="mt-4 flex-row gap-3"><View className="flex-1"><Label text="Inicio"><Input value={inicio} onChangeText={setInicio} /></Label></View><View className="flex-1"><Label text="Fin"><Input value={fin} onChangeText={setFin} placeholder="Opcional" /></Label></View></View><Label text="Descripción"><TextInput value={descripcion} onChangeText={setDescripcion} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Action label={updateMutation.isPending ? 'Guardando…' : 'Guardar cambios'} disabled={!valid || updateMutation.isPending} onPress={() => updateMutation.mutate()} /></Section><Section title="Siembras vinculadas"><Text className="text-sm text-slate-500">Seleccioná las siembras que querés sumar a esta campaña.</Text>{seedsQuery.isLoading ? <ActivityIndicator className="mt-4" color="#15803d" /> : (seedsQuery.data ?? []).length === 0 ? <Text className="mt-4 text-sm text-slate-500">No hay siembras disponibles en la organización.</Text> : <View className="mt-4 gap-2">{(seedsQuery.data ?? []).map((seed) => { const selected = selectedSeeds.includes(seed.id); return <Pressable key={seed.id} className={`rounded-xl border p-3 ${selected ? 'border-emerald-700 bg-emerald-50' : 'border-slate-200 bg-white'}`} onPress={() => setSelectedSeeds((current) => selected ? current.filter((seedId) => seedId !== seed.id) : [...current, seed.id])}><Text className="font-semibold text-slate-800">{seed.nombre}</Text><Text className={`mt-1 text-sm font-semibold ${selected ? 'text-emerald-800' : 'text-slate-500'}`}>{selected ? 'VINCULADA' : 'VINCULAR'}</Text></Pressable>; })}</View>}<Action label={assignMutation.isPending ? 'Vinculando…' : 'Guardar siembras'} disabled={assignMutation.isPending} onPress={() => assignMutation.mutate()} /></Section><Pressable className="mt-5 items-center rounded-xl bg-red-50 px-5 py-4 disabled:opacity-50" disabled={deleteMutation.isPending} onPress={() => Alert.alert('Eliminar campaña', `¿Eliminar ${campaign.nombre}?`, [{ text: 'Volver', style: 'cancel' }, { text: 'Eliminar', style: 'destructive', onPress: () => deleteMutation.mutate() }])}><Text className="font-semibold text-red-700">Eliminar campaña</Text></Pressable></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View className="mt-6 rounded-2xl bg-white p-5"><Text className="text-lg font-bold text-slate-900">{title}</Text><View className="mt-3">{children}</View></View>; } function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; } function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View className="mt-2"><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; } function Action({ label, disabled, onPress }: { label: string; disabled: boolean; onPress: () => void }) { return <Pressable className="mt-5 items-center rounded-xl bg-emerald-700 px-4 py-3 disabled:opacity-50" disabled={disabled} onPress={onPress}><Text className="font-semibold text-white">{label}</Text></Pressable>; } function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando campaña…</Text></View>; } function ErrorView({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar la campaña</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={onRetry}><Text className="font-semibold text-white">Reintentar</Text></Pressable></View>; }
