import { ActivityIndicator, Pressable, RefreshControl, ScrollView, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Href, router } from 'expo-router';
import { getCampanias } from '@/api/campanias.api';
import { getApiErrorMessage } from '@/api/errors';
import { AccessRestricted } from '@/components/AccessRestricted';
import { useAuthStore } from '@/store/auth.store';

export default function CampaniasScreen() {
  const orgId = useAuthStore((state) => state.organizacionActivaId); const isOwner = useAuthStore((state) => state.isOwner()); const currentOrganization = useAuthStore((state) => state.currentOrganization); const org = currentOrganization(); const isPro = org?.plan === 'PRO'; const query = useQuery({ queryKey: ['campanias', orgId], queryFn: getCampanias, enabled: Boolean(orgId && isOwner && isPro) });
  if (!isOwner) return <AccessRestricted title="Campañas" />;
  if (!isPro) return <ProRequired />;
  if (query.isLoading) return <Loading />;
  if (query.isError) return <ErrorView error={query.error} onRetry={() => void query.refetch()} />;
  const campaigns = query.data ?? [];
  return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ paddingBottom: 32 }} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} />}><View className="bg-emerald-800 px-6 pb-7 pt-16"><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="text-3xl font-bold text-white">Campañas</Text><Text className="mt-2 text-sm text-emerald-100">Agrupá siembras y seguí cada ciclo productivo.</Text></View><Pressable className="rounded-xl bg-white px-3 py-3" onPress={() => router.push('/(app)/campanias/nueva' as Href)}><Text className="font-semibold text-emerald-800">+ Campaña</Text></Pressable></View></View><View className="px-5 pt-5"><Text className="text-sm font-bold uppercase tracking-widest text-slate-500">Campañas ({campaigns.length})</Text><View className="mt-3 gap-3">{campaigns.length === 0 ? <Empty onAdd={() => router.push('/(app)/campanias/nueva' as Href)} /> : campaigns.map((campaign) => <Pressable key={campaign.id} className="rounded-2xl bg-white p-5" onPress={() => router.push({ pathname: '/(app)/campanias/[campaniaId]', params: { campaniaId: String(campaign.id) } } as unknown as Href)}><Text className="text-lg font-bold text-slate-900">{campaign.nombre}</Text><Text className="mt-1 text-sm text-slate-500">{date(campaign.fechaInicio)}{campaign.fechaFin ? ` → ${date(campaign.fechaFin)}` : ' · En curso'}</Text>{campaign.descripcion && <Text className="mt-3 text-sm text-slate-600">{campaign.descripcion}</Text>}<View className="mt-4 border-t border-slate-100 pt-3"><Text className="text-sm font-semibold text-emerald-800">{campaign.siembras.length} siembras asignadas</Text></View></Pressable>)}</View></View></ScrollView>;
}
function ProRequired() { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-2xl font-bold text-slate-900">Campañas es una función Pro</Text><Text className="mt-3 text-center text-sm leading-5 text-slate-600">Actualizá el plan de esta organización para agrupar siembras y seguir cada ciclo productivo.</Text></View>; }
function Empty({ onAdd }: { onAdd: () => void }) { return <View className="items-center rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12"><Text className="text-4xl">◒</Text><Text className="mt-4 text-lg font-bold text-slate-900">No hay campañas creadas</Text><Pressable className="mt-5 rounded-xl bg-emerald-700 px-4 py-3" onPress={onAdd}><Text className="font-semibold text-white">Crear campaña</Text></Pressable></View>; } function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando campañas…</Text></View>; } function ErrorView({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar las campañas</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={onRetry}><Text className="font-semibold text-white">Reintentar</Text></Pressable></View>; } function date(value: string) { return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }
