import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { crearCampania } from '@/api/campanias.api';
import { getApiErrorMessage } from '@/api/errors';
import { useAuthStore } from '@/store/auth.store';
const today = () => new Date().toISOString().slice(0, 10);
export default function NuevaCampaniaScreen() { const orgId = useAuthStore((state) => state.organizacionActivaId); const qc = useQueryClient(); const [nombre, setNombre] = useState(''); const [inicio, setInicio] = useState(today()); const [fin, setFin] = useState(''); const [descripcion, setDescripcion] = useState(''); const mutation = useMutation({ mutationFn: () => crearCampania({ nombre: nombre.trim(), fechaInicio: inicio, fechaFin: fin || undefined, descripcion: descripcion.trim() || undefined }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['campanias', orgId] }); Alert.alert('Campaña creada', 'Ahora podés asignarle siembras desde su detalle.'); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos crear la campaña', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) }); const valid = nombre.trim().length >= 3 && /^\d{4}-\d{2}-\d{2}$/.test(inicio) && (!fin || /^\d{4}-\d{2}-\d{2}$/.test(fin)); return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Campañas</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">Nueva campaña</Text><View className="mt-7 rounded-2xl bg-white p-5"><Label text="Nombre"><Input value={nombre} onChangeText={setNombre} placeholder="Ej: Campaña 2026/2027" /></Label><View className="mt-5 flex-row gap-3"><View className="flex-1"><Label text="Fecha inicio"><Input value={inicio} onChangeText={setInicio} placeholder="AAAA-MM-DD" /></Label></View><View className="flex-1"><Label text="Fecha fin"><Input value={fin} onChangeText={setFin} placeholder="Opcional" /></Label></View></View><Label text="Descripción"><TextInput value={descripcion} onChangeText={setDescripcion} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Pressable className="mt-7 items-center rounded-xl bg-emerald-700 px-5 py-4 disabled:opacity-50" disabled={!valid || mutation.isPending} onPress={() => mutation.mutate()}><Text className="font-semibold text-white">{mutation.isPending ? 'Creando…' : 'Crear campaña'}</Text></Pressable></View></ScrollView>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; } function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View className="mt-5"><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; }
