import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { Bird, Egg, Loader2, Plus, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import {
  avicolaApi,
  type CreateGalponAvicolaDto,
  type CreateRegistroAvicolaDto,
  type GalponAvicola,
  type TipoGalponAvicola,
} from '../../api/avicola.api';

const TIPOS: Record<TipoGalponAvicola, string> = { POSTURA: 'Postura', ENGORDE: 'Engorde', RECRIA: 'Recría', OTRO: 'Otro' };
const newGalpon: CreateGalponAvicolaDto = { nombre: '', tipo: 'POSTURA' };
const newRegistro: CreateRegistroAvicolaDto = { fecha: new Date().toISOString().slice(0, 10), avesPresentes: 0, huevos: 0, mortandad: 0, alimentoKg: 0 };

export default function AvicolaPage() {
  const { orgId } = useParams<{ orgId: string }>();
  const organizacionId = Number(orgId);
  const queryClient = useQueryClient();
  const [crearGalpon, setCrearGalpon] = useState(false);
  const [registroGalpon, setRegistroGalpon] = useState<GalponAvicola | null>(null);
  const [galponForm, setGalponForm] = useState<CreateGalponAvicolaDto>(newGalpon);
  const [registroForm, setRegistroForm] = useState<CreateRegistroAvicolaDto>(newRegistro);

  const galponesQuery = useQuery({ queryKey: ['avicola', organizacionId], queryFn: avicolaApi.getAll });
  const resumenQuery = useQuery({ queryKey: ['avicola-resumen', organizacionId], queryFn: avicolaApi.getResumen });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['avicola', organizacionId] }); queryClient.invalidateQueries({ queryKey: ['avicola-resumen', organizacionId] }); };
  const galponMutation = useMutation({ mutationFn: avicolaApi.createGalpon, onSuccess: () => { refresh(); setCrearGalpon(false); setGalponForm(newGalpon); toast.success('Galpón registrado.'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo crear el galpón.') });
  const registroMutation = useMutation({ mutationFn: ({ galponId, dto }: { galponId: number; dto: CreateRegistroAvicolaDto }) => avicolaApi.createRegistro(galponId, dto), onSuccess: () => { refresh(); setRegistroGalpon(null); setRegistroForm(newRegistro); toast.success('Registro diario guardado.'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo guardar el registro.') });
  const deleteMutation = useMutation({ mutationFn: avicolaApi.removeRegistro, onSuccess: () => { refresh(); toast.success('Registro eliminado.'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo eliminar el registro.') });
  const resumen = resumenQuery.data;

  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-amber-600">Producción especializada</p><h1 className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">Avícola</h1><p className="mt-1 max-w-2xl text-sm text-gray-500 dark:text-gray-400">Organizá los galpones y registrá cada día aves presentes, postura, alimento y mortandad.</p></div><button type="button" onClick={() => setCrearGalpon(true)} className="inline-flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-amber-700"><Plus size={16} />Nuevo galpón</button></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Egg} label="Huevos hoy" value={(resumen?.huevosHoy ?? 0).toLocaleString('es-AR')} /><Metric icon={Egg} label="Huevos del mes" value={(resumen?.huevosMes ?? 0).toLocaleString('es-AR')} /><Metric icon={Bird} label="Galpones activos" value={resumen?.galponesActivos ?? 0} /><Metric icon={Bird} label="Mortandad del mes" value={resumen?.mortandadMes ?? 0} /></section>
    {galponesQuery.isLoading ? <div className="flex justify-center py-20"><Loader2 size={32} className="animate-spin text-amber-600" /></div> : !galponesQuery.data?.length ? <EmptyState onCreate={() => setCrearGalpon(true)} /> : <section className="grid gap-4 lg:grid-cols-2">{galponesQuery.data.map((galpon) => <GalponCard key={galpon.id} galpon={galpon} onRegistro={() => { setRegistroGalpon(galpon); setRegistroForm(newRegistro); }} onDelete={(id) => deleteMutation.mutate(id)} deleting={deleteMutation.isPending} />)}</section>}
    {crearGalpon && <Dialog title="Nuevo galpón" onClose={() => setCrearGalpon(false)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); galponMutation.mutate(galponForm); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre *"><input required className="input" placeholder="Ej: Galpón 1" value={galponForm.nombre} onChange={(event) => setGalponForm({ ...galponForm, nombre: event.target.value })} /></Field><Field label="Tipo *"><select className="input" value={galponForm.tipo} onChange={(event) => setGalponForm({ ...galponForm, tipo: event.target.value as TipoGalponAvicola })}>{Object.entries(TIPOS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Capacidad de aves"><input type="number" min="1" className="input" value={galponForm.capacidad ?? ''} onChange={(event) => setGalponForm({ ...galponForm, capacidad: event.target.value ? Number(event.target.value) : undefined })} placeholder="Opcional" /></Field></div><Field label="Observaciones"><textarea rows={3} className="input resize-none" value={galponForm.observaciones ?? ''} onChange={(event) => setGalponForm({ ...galponForm, observaciones: event.target.value })} placeholder="Opcional" /></Field><Actions onCancel={() => setCrearGalpon(false)} loading={galponMutation.isPending} label="Crear galpón" /></form></Dialog>}
    {registroGalpon && <Dialog title={'Registro diario - ' + registroGalpon.nombre} onClose={() => setRegistroGalpon(null)}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); registroMutation.mutate({ galponId: registroGalpon.id, dto: registroForm }); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha *"><input required type="date" className="input" value={registroForm.fecha} onChange={(event) => setRegistroForm({ ...registroForm, fecha: event.target.value })} /></Field><Field label="Aves presentes *"><input required type="number" min="0" className="input" value={registroForm.avesPresentes || ''} onChange={(event) => setRegistroForm({ ...registroForm, avesPresentes: Number(event.target.value) || 0 })} /></Field><Field label="Huevos"><input type="number" min="0" className="input" value={registroForm.huevos || ''} onChange={(event) => setRegistroForm({ ...registroForm, huevos: Number(event.target.value) || 0 })} /></Field><Field label="Mortandad"><input type="number" min="0" className="input" value={registroForm.mortandad || ''} onChange={(event) => setRegistroForm({ ...registroForm, mortandad: Number(event.target.value) || 0 })} /></Field><Field label="Alimento (kg)"><input type="number" min="0" step="0.1" className="input" value={registroForm.alimentoKg || ''} onChange={(event) => setRegistroForm({ ...registroForm, alimentoKg: Number(event.target.value) || 0 })} /></Field><Field label="Peso promedio (g)"><input type="number" min="0" step="0.1" className="input" value={registroForm.pesoPromedioGr ?? ''} onChange={(event) => setRegistroForm({ ...registroForm, pesoPromedioGr: event.target.value ? Number(event.target.value) : undefined })} /></Field></div><Field label="Observaciones"><textarea rows={2} className="input resize-none" value={registroForm.observaciones ?? ''} onChange={(event) => setRegistroForm({ ...registroForm, observaciones: event.target.value })} placeholder="Opcional" /></Field><Actions onCancel={() => setRegistroGalpon(null)} loading={registroMutation.isPending} label="Guardar registro" /></form></Dialog>}
  </div>;
}

function GalponCard({ galpon, onRegistro, onDelete, deleting }: { galpon: GalponAvicola; onRegistro: () => void; onDelete: (id: number) => void; deleting: boolean }) { const ultimo = galpon.registros[0]; return <article className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-gray-900 dark:text-white">{galpon.nombre}</h2><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{TIPOS[galpon.tipo]}{galpon.capacidad ? ' · Capacidad: ' + galpon.capacidad.toLocaleString('es-AR') : ''}</p></div><button type="button" onClick={onRegistro} className="inline-flex items-center gap-2 rounded-lg bg-amber-600 px-3 py-2 text-sm font-semibold text-white hover:bg-amber-700"><Plus size={15} />Carga diaria</button></div>{ultimo ? <div className="mt-4 grid gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-950 dark:bg-amber-950/25 dark:text-amber-100 sm:grid-cols-3"><span>{formatDate(ultimo.fecha)}</span><span className="font-semibold">{ultimo.huevos.toLocaleString('es-AR')} huevos</span><span>{ultimo.avesPresentes.toLocaleString('es-AR')} aves</span></div> : <p className="mt-4 rounded-xl border border-dashed border-gray-200 p-3 text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">Sin registros diarios todavía.</p>}<div className="mt-4 border-t border-gray-100 pt-3 dark:border-gray-700">{galpon.registros.slice(0, 5).map((registro) => <div key={registro.id} className="flex items-center justify-between gap-3 py-2 text-sm text-gray-600 dark:text-gray-300"><span>{formatDate(registro.fecha)} · {registro.huevos.toLocaleString('es-AR')} huevos · {registro.alimentoKg} kg</span><button type="button" disabled={deleting} onClick={() => onDelete(registro.id)} className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50" title="Eliminar registro"><Trash2 size={15} /></button></div>)}</div></article>; }
function Metric({ icon: Icon, label, value }: { icon: typeof Egg; label: string; value: number | string }) { return <div className="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><Icon size={18} className="text-amber-600" /><p className="mt-3 text-2xl font-bold text-gray-900 dark:text-white">{value}</p><p className="text-sm text-gray-500 dark:text-gray-400">{label}</p></div>; }
function EmptyState({ onCreate }: { onCreate: () => void }) { return <div className="rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-16 text-center dark:border-gray-700 dark:bg-gray-800"><Bird size={38} className="mx-auto text-amber-600" /><h2 className="mt-4 text-lg font-bold text-gray-900 dark:text-white">Todavía no hay galpones registrados</h2><p className="mx-auto mt-2 max-w-md text-sm text-gray-500 dark:text-gray-400">Creá el primer galpón para llevar su producción y sus datos diarios.</p><button type="button" onClick={onCreate} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-amber-700"><Plus size={16} />Crear primer galpón</button></div>; }
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4" onClick={onClose}><div className="mx-auto my-6 w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl dark:bg-gray-800" onClick={(event) => event.stopPropagation()}><h2 className="mb-5 text-lg font-bold text-gray-900 dark:text-white">{title}</h2>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-gray-700 dark:text-gray-200"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Actions({ onCancel, loading, label }: { onCancel: () => void; loading: boolean; label: string }) { return <div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2 text-sm font-semibold text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700">Cancelar</button><button disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700 disabled:opacity-60">{loading && <Loader2 size={15} className="animate-spin" />}{label}</button></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium' }).format(new Date(value)); }
