ALTER TABLE "Usuario"
ADD COLUMN "fotoPerfilPosicionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "fotoPerfilPosicionY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "fotoPerfilEscala" DOUBLE PRECISION NOT NULL DEFAULT 1;
