import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { actualizarInsumo, getInsumo } from '@/api/insumos.api';
import { getApiErrorMessage } from '@/api/errors';
import { TIPO_INSUMO_LABEL, TIPOS_INSUMO, type TipoInsumo } from '@/types/insumos';

export default function InsumoDetailScreen() { const { insumoId } = useLocalSearchParams<{ insumoId: string }>(); const id = Number(insumoId); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['insumo', id], queryFn: () => getInsumo(id), enabled: Number.isInteger(id) && id > 0 }); const [nombre, setNombre] = useState(''); const [tipo, setTipo] = useState<TipoInsumo>('FERTILIZANTE'); const [unidad, setUnidad] = useState(''); const [descripcion, setDescripcion] = useState(''); useEffect(() => { if (query.data) { setNombre(query.data.nombre); setTipo(query.data.tipo); setUnidad(query.data.unidad); setDescripcion(query.data.descripcion ?? ''); } }, [query.data]); const mutation = useMutation({ mutationFn: () => actualizarInsumo(id, { nombre: nombre.trim(), tipo, unidad: unidad.trim(), descripcion: descripcion.trim() || undefined }), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['insumos'] }), queryClient.invalidateQueries({ queryKey: ['insumo', id] })]); Alert.alert('Insumo actualizado', 'Los cambios ya están disponibles en las aplicaciones.'); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos guardar los cambios', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) }); if (query.isLoading) return <Loading />; if (query.isError || !query.data) return <LoadError error={query.error} />; return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Insumos</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">Editar insumo</Text><View className="mt-7 rounded-2xl bg-white p-5"><Label text="Nombre"><Input value={nombre} onChangeText={setNombre} /></Label><Label text="Tipo"><View className="mt-2 flex-row flex-wrap gap-2">{TIPOS_INSUMO.map((item) => <Pressable key={item} className={`rounded-full px-3 py-2 ${tipo === item ? 'bg-emerald-700' : 'bg-slate-100'}`} onPress={() => setTipo(item)}><Text className={`text-sm font-semibold ${tipo === item ? 'text-white' : 'text-slate-700'}`}>{TIPO_INSUMO_LABEL[item]}</Text></Pressable>)}</View></Label><Label text="Unidad"><Input value={unidad} onChangeText={setUnidad} /></Label><Label text="Descripción"><TextInput value={descripcion} onChangeText={setDescripcion} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Pressable className="mt-7 items-center rounded-xl bg-emerald-700 px-5 py-4 disabled:opacity-50" disabled={nombre.trim().length < 2 || !unidad.trim() || mutation.isPending} onPress={() => mutation.mutate()}><Text className="font-semibold text-white">{mutation.isPending ? 'Guardando…' : 'Guardar cambios'}</Text></Pressable></View></ScrollView>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; } function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View className="mt-5"><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; } function Loading() { return <View className="flex-1 items-center justify-center bg-slate-50"><ActivityIndicator color="#15803d" size="large" /><Text className="mt-3 text-sm text-slate-500">Cargando insumo…</Text></View>; } function LoadError({ error }: { error: unknown }) { return <View className="flex-1 items-center justify-center bg-slate-50 px-6"><Text className="text-center text-xl font-bold text-slate-900">No pudimos cargar el insumo</Text><Text className="mt-2 text-center text-sm text-slate-500">{getApiErrorMessage(error, 'Intentá nuevamente.')}</Text><Pressable className="mt-6 rounded-xl bg-emerald-700 px-5 py-3" onPress={() => router.back()}><Text className="font-semibold text-white">Volver</Text></Pressable></View>; }
