import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { crearInsumo } from '@/api/insumos.api';
import { getApiErrorMessage } from '@/api/errors';
import { TIPO_INSUMO_LABEL, TIPOS_INSUMO, type TipoInsumo } from '@/types/insumos';

export default function NuevoInsumoScreen() { const queryClient = useQueryClient(); const [nombre, setNombre] = useState(''); const [tipo, setTipo] = useState<TipoInsumo>('FERTILIZANTE'); const [unidad, setUnidad] = useState(''); const [descripcion, setDescripcion] = useState(''); const mutation = useMutation({ mutationFn: () => crearInsumo({ nombre: nombre.trim(), tipo, unidad: unidad.trim(), descripcion: descripcion.trim() || undefined }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['insumos'] }); Alert.alert('Insumo creado', 'Ya podés seleccionarlo al registrar una aplicación.'); router.back(); }, onError: (error: unknown) => Alert.alert('No pudimos crear el insumo', getApiErrorMessage(error, 'Revisá los datos e intentá nuevamente.')) }); return <ScrollView className="flex-1 bg-slate-50" contentContainerStyle={{ padding: 20, paddingTop: 60, paddingBottom: 36 }}><Pressable onPress={() => router.back()}><Text className="text-sm font-semibold text-emerald-800">‹ Insumos</Text></Pressable><Text className="mt-5 text-3xl font-bold text-slate-900">Nuevo insumo</Text><View className="mt-7 rounded-2xl bg-white p-5"><Label text="Nombre"><Input value={nombre} onChangeText={setNombre} placeholder="Ej: Urea granulada" autoFocus /></Label><Label text="Tipo"><View className="mt-2 flex-row flex-wrap gap-2">{TIPOS_INSUMO.map((item) => <Pressable key={item} className={`rounded-full px-3 py-2 ${tipo === item ? 'bg-emerald-700' : 'bg-slate-100'}`} onPress={() => setTipo(item)}><Text className={`text-sm font-semibold ${tipo === item ? 'text-white' : 'text-slate-700'}`}>{TIPO_INSUMO_LABEL[item]}</Text></Pressable>)}</View></Label><Label text="Unidad"><Input value={unidad} onChangeText={setUnidad} placeholder="Ej: kg, litros o dosis" /></Label><Label text="Descripción"><TextInput value={descripcion} onChangeText={setDescripcion} multiline textAlignVertical="top" placeholder="Opcional" placeholderTextColor="#94a3b8" className="mt-2 min-h-24 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" /></Label><Pressable className="mt-7 items-center rounded-xl bg-emerald-700 px-5 py-4 disabled:opacity-50" disabled={nombre.trim().length < 2 || !unidad.trim() || mutation.isPending} onPress={() => mutation.mutate()}><Text className="font-semibold text-white">{mutation.isPending ? 'Creando…' : 'Crear insumo'}</Text></Pressable></View></ScrollView>; }
function Input(props: React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#94a3b8" className="mt-2 rounded-xl border border-slate-200 px-4 py-3 text-base text-slate-900" />; } function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View className="mt-5"><Text className="text-sm font-semibold text-slate-800">{text}</Text>{children}</View>; }
